apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-pvc
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: my-disk-data
    fsType: ext4
